In [1]:
import pandas as pd 

df = pd.read_excel("computadores.xlsx")
display(df)

                                                 marca        preco
0    Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...  R$ 4.999,00
1    Monitor Gamer KBM! Gaming MG800 34" QHD, Ultra...  R$ 1.599,90
2    Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...  R$ 6.499,99
3    Monitor Profissional Philips 49" 2K QHD, Ultra...  R$ 7.499,99
4    Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...  R$ 1.699,99
..                                                 ...          ...
183  Monitor Gamer Samsung 22" FHD,100 Hz, HDMI, VG...    R$ 603,57
184  Monitor Samsung 32" FHD,75 Hz,Freesync, HDMI, ...  R$ 1.059,27
185  Monitor Gamer Samsung 27" FHD,100 Hz, HDMI, VG...    R$ 705,87
186  Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...  R$ 2.111,12
187  Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...  R$ 4.689,99

[188 rows x 2 columns]

In [3]:
cores = [
"amarelo", "amarela", "azul", "branco", "branca", "cinza", "creme", "dourado", "laranja", "marrom", "preto", 
"rosa","roxo", "verde", "vermelho", "bege","graphite", "geada", "uva", "grey", "yellow", "blue", "silver",
"red", "black","off white","white", "green", "purple","orange", "white", "pink","fuchsia", 
"orchid","aqua","azure","beige","darkred","coral","preta"
]

def extrair_cor(texto):
    texto = texto.lower()
    for cor in cores:
        if cor in texto:
            return cor
    return "Desconhecida"

df["cor_principal"] = df["marca"].apply(extrair_cor)
display(df[["marca", "cor_principal"]])

                                                 marca cor_principal
0    Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...         preto
1    Monitor Gamer KBM! Gaming MG800 34" QHD, Ultra...         preto
2    Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...  Desconhecida
3    Monitor Profissional Philips 49" 2K QHD, Ultra...         preto
4    Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...  Desconhecida
..                                                 ...           ...
183  Monitor Gamer Samsung 22" FHD,100 Hz, HDMI, VG...         preto
184  Monitor Samsung 32" FHD,75 Hz,Freesync, HDMI, ...         preto
185  Monitor Gamer Samsung 27" FHD,100 Hz, HDMI, VG...         preto
186  Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...         preto
187  Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...  Desconhecida

[188 rows x 2 columns]

In [4]:
contagem = df['cor_principal'].str.contains('Desconhecida', case=False, na=False).sum() 

print(f'A palavra "desconhecida" aparece {contagem} vezes na coluna.')

A palavra "desconhecida" aparece 80 vezes na coluna.

In [5]:
df['cor_principal'] = df['cor_principal'].str.title()
display(df)

,marca,preco,cor_principal
0,Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...,"R$ 4.999,00",Preto
1,"Monitor Gamer KBM! Gaming MG800 34"" QHD, Ultra...","R$ 1.599,90",Preto
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida
3,"Monitor Profissional Philips 49"" 2K QHD, Ultra...","R$ 7.499,99",Preto
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida
...,...,...,...
183,"Monitor Gamer Samsung 22"" FHD,100 Hz, HDMI, VG...","R$ 603,57",Preto
184,"Monitor Samsung 32"" FHD,75 Hz,Freesync, HDMI, ...","R$ 1.059,27",Preto
185,"Monitor Gamer Samsung 27"" FHD,100 Hz, HDMI, VG...","R$ 705,87",Preto
186,Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...,"R$ 2.111,12",Preto
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida

In [6]:
df_filtrado = df[df['cor_principal'].str.contains('desconhecida', case=False, na=False)]

display(df_filtrado)

,marca,preco,cor_principal
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida
6,Notebook Gamer ASUS ROG Strix G16 Intel Core i...,"R$ 8.199,00",Desconhecida
7,"Monitor Gamer Husky Storm 27' LED, Curvo, 180H...","R$ 945,90",Desconhecida
9,"Monitor Gamer Husky Blizzard 27' LED Full HD, ...","R$ 1.099,90",Desconhecida
...,...,...,...
173,"Notebook Samsung Galaxy Book4 Pro, WINDOWS 11 ...","R$ 6.974,07",Desconhecida
175,Notebook Asus Tuf Gaming F15 Fx507vv RTX4060 I...,"R$ 8.249,99",Desconhecida
178,Notebook Asus Zenbook S 14 OLED Ux5406sa Intel...,"R$ 12.759,12",Desconhecida
179,"Notebook Asus Tuf Gaming F15 Fx507vv, Intel Co...","R$ 7.339,99",Desconhecida
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida

In [7]:
df['possui_RAM'] = df['marca'].str.contains('RAM', case=False, na=False)

display(df)

,marca,preco,cor_principal,possui_RAM
0,Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...,"R$ 4.999,00",Preto,True
1,"Monitor Gamer KBM! Gaming MG800 34"" QHD, Ultra...","R$ 1.599,90",Preto,False
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida,False
3,"Monitor Profissional Philips 49"" 2K QHD, Ultra...","R$ 7.499,99",Preto,False
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida,False
...,...,...,...,...
183,"Monitor Gamer Samsung 22"" FHD,100 Hz, HDMI, VG...","R$ 603,57",Preto,False
184,"Monitor Samsung 32"" FHD,75 Hz,Freesync, HDMI, ...","R$ 1.059,27",Preto,False
185,"Monitor Gamer Samsung 27"" FHD,100 Hz, HDMI, VG...","R$ 705,87",Preto,False
186,Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...,"R$ 2.111,12",Preto,False
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida,True

In [8]:
import re

In [9]:
df['quantidade_RAM'] = df['marca'].str.extract(r'(\d+)\s*GB\s*RAM', flags=re.IGNORECASE) # Todos anúncios que possuem a palavra RAM faz uma captura 

display(df)

,marca,preco,cor_principal,possui_RAM,quantidade_RAM
0,Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...,"R$ 4.999,00",Preto,True,8
1,"Monitor Gamer KBM! Gaming MG800 34"" QHD, Ultra...","R$ 1.599,90",Preto,False,NaN
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida,False,NaN
3,"Monitor Profissional Philips 49"" 2K QHD, Ultra...","R$ 7.499,99",Preto,False,NaN
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida,False,NaN
...,...,...,...,...,...
183,"Monitor Gamer Samsung 22"" FHD,100 Hz, HDMI, VG...","R$ 603,57",Preto,False,NaN
184,"Monitor Samsung 32"" FHD,75 Hz,Freesync, HDMI, ...","R$ 1.059,27",Preto,False,NaN
185,"Monitor Gamer Samsung 27"" FHD,100 Hz, HDMI, VG...","R$ 705,87",Preto,False,NaN
186,Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...,"R$ 2.111,12",Preto,False,NaN
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida,True,8

In [10]:
print(df.columns.tolist()) # Mostra o nome de todas as colunas que tem no excel

['marca', 'preco', 'cor_principal', 'possui_RAM', 'quantidade_RAM']

In [11]:
df.to_excel('computadores.xlsx', index=False) # Salva tudo no arquivo do excel 

display(df)

,marca,preco,cor_principal,possui_RAM,quantidade_RAM
0,Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...,"R$ 4.999,00",Preto,True,8
1,"Monitor Gamer KBM! Gaming MG800 34"" QHD, Ultra...","R$ 1.599,90",Preto,False,NaN
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida,False,NaN
3,"Monitor Profissional Philips 49"" 2K QHD, Ultra...","R$ 7.499,99",Preto,False,NaN
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida,False,NaN
...,...,...,...,...,...
183,"Monitor Gamer Samsung 22"" FHD,100 Hz, HDMI, VG...","R$ 603,57",Preto,False,NaN
184,"Monitor Samsung 32"" FHD,75 Hz,Freesync, HDMI, ...","R$ 1.059,27",Preto,False,NaN
185,"Monitor Gamer Samsung 27"" FHD,100 Hz, HDMI, VG...","R$ 705,87",Preto,False,NaN
186,Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...,"R$ 2.111,12",Preto,False,NaN
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida,True,8

In [12]:
df['quantidade_RAM'] = df['quantidade_RAM'].fillna('Não possui') 

display(df)
# Na coluna possui_RAM os espaços em branco passa a ficar como "Não possui"

,marca,preco,cor_principal,possui_RAM,quantidade_RAM
0,Notebook Gamer Acer Nitro V15 ANV15-51-7837 In...,"R$ 4.999,00",Preto,True,8
1,"Monitor Gamer KBM! Gaming MG800 34"" QHD, Ultra...","R$ 1.599,90",Preto,False,Não possui
2,"Monitor Gamer Asus ROG Swift 49' LED, Ultra Wi...","R$ 6.499,99",Desconhecida,False,Não possui
3,"Monitor Profissional Philips 49"" 2K QHD, Ultra...","R$ 7.499,99",Preto,False,Não possui
4,"Monitor Gamer Asus TUF 31.5 LED 2K QHD, 165Hz,...","R$ 1.699,99",Desconhecida,False,Não possui
...,...,...,...,...,...
183,"Monitor Gamer Samsung 22"" FHD,100 Hz, HDMI, VG...","R$ 603,57",Preto,False,Não possui
184,"Monitor Samsung 32"" FHD,75 Hz,Freesync, HDMI, ...","R$ 1.059,27",Preto,False,Não possui
185,"Monitor Gamer Samsung 27"" FHD,100 Hz, HDMI, VG...","R$ 705,87",Preto,False,Não possui
186,Notebook Lenovo V14 G4 Amd Ryzen 3 7320u 8GB 2...,"R$ 2.111,12",Preto,False,Não possui
187,"Notebook Asus Tuf Gaming A15, AMD Ryzen 7-7435...","R$ 4.689,99",Desconhecida,True,8